### PR TITLE
clippy and gated rule enforcement

### PR DESCRIPTION
**Pull request by drahnr**
During development quite a few - in practice - annoying properties got addressed.

### CODE REVIEW

**Review by sandreim — APPROVED** [review]
LGTM! I would enable these 2 features by default.

**Comment by vstakhov** [comment]
> LGTM! I would enable these 2 features by default.

As far as I see they were enabled by default (without possibility to be disabled) before this PR. So I also think it would be better to enable them by default.

**Review by vstakhov — APPROVED** [review]
It looks good indeed, but I also think that these features should be default enabled.

**Comment by drahnr** [comment]
On second thought: It could also be an argument to `#[orchestra(a, b, c, deny_unsent, deny_unconsumed)]` although that could be done on-top :cherries:

**Pull request merged**
