### PR TITLE
feat/dotgraph: implement dot graph rendering as part of the proc-macro

### PR DESCRIPTION
**Pull request by drahnr**
~~The generated files are far from perfect, `layout-rs` is not working out too well..~~

The generated files only deviate in the sense that double circles are not rendered accurately, otherwise the output looks fine.

The `png` rendered lacks text render capabilities, and is hence feature gated for now.

### CODE REVIEW

**Comment by sandreim** [comment]
For `Polkadot` the output of the graph is quite hard to reason about, so one improvement I was thinking about is to add some parameter such that only selected subsystems are present in the graph. WDYT ?

**Comment by drahnr** [comment]
@vstakhov @sandreim if you could give it a glance :)

There are trade-offs:

+ self sufficient `svg` generation / independence of the environment
- slightly increased build time due to additional dependencies

**Comment by vstakhov** [comment]
Do we really need a png output counting that the conversion svg->png is a trivial thing?

**Comment by drahnr** [comment]
> Do we really need a png output counting that the conversion svg->png is a trivial thing?

Up for debate, happy to delete it

**Comment by drahnr** [comment]
@vstakhov removed the png generation, (another) review would be much appreciated

**Review by vstakhov — APPROVED** [review]

**Pull request merged**
